### ISSUE TITLE
对比模型请教

### ISSUE THREAD

**Issue by joyjoy2026** [Crescent-Ao/MPANet#1]
四月伊始, 在这里预祝您有一个愉快的四月^_^.

我叫陈壮, 目前同样正在研究红外小目标检测的相关问题, 看到您公开的MPANet后我感到十分振奋, 这真是一项极具创造性的工作, 祝您论文投稿顺利.

拜读您的工作后, 我相信您肯定要对比ALCNet这一模型, 这一定是我们对比模型中一座绕不过的"大山".

可是这个模型的作者戴博士习惯使用MXNET, 这对于习惯Pytorch的我来说十分煎熬, 尝试转化为Pytorch版本后也是问题百出.

因此冒昧来信, 希望您能够开源您实现的Pytorch版本的ALCNet, 我相信这对于整个研究领域内的人来说都是一件值得喝彩的壮举.

再次感谢您在红外小目标目标领域内的工作,  以及您热爱&&共享的开源精神，这为同样研究这个问题的我们提供了宝贵的思路与优质数据集.

祝学业顺利 生活愉快.

陈壮

**Comment by Crescent-Ao** [comment]
很抱歉，我去年尝试过复现ALCNET，但是MXNET框架去年对于30系显卡支持的缘故，MPANet并没有和ALCNET对比，这也是比较大遗憾之一，去年的年中DNANet实验结果已经超过ALCNET的相关结论，我也在等待戴博士的ALCNet的复现结构。MPANet代码并没有开放完全，近期会在IGARSS结束之后放出相关代码。MPANET对比实验包括：MDvsFA，DNANET，ACM。张博士的AGPCNET在我后面的工作中也会出现对比结论，并且开源集合目前所有的评估方法。

**Comment by joyjoy2026** [comment]
好的好的 祝论文&&毕业顺利: D
